language: python
matrix:
  include:
    - python: 3.8
      arch: amd64
    - python: 3.8
      arch: arm64

install: python setup.py install
script:
- python setup.py test
- source ci_scripts/create_doc.sh $TRAVIS_BRANCH "doc_result"

# For more info regarding the deploy process and the github token, look at:
# https://docs.travis-ci.com/user/deployment/pages/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: false
  committer-from-gh: true
  on:
    all_branches: true
    condition: $doc_result = "success"
  local_dir: docs/build/html
